// flow-typed signature: 659a59954692351c75fabc3da44d9fc2
// flow-typed version: <<STUB>>/config-webpack_v^1.0.4/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'config-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'config-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'config-webpack/dist/ConfigWebpackPlugin' {
  declare module.exports: any;
}

declare module 'config-webpack/src/ConfigWebpackPlugin' {
  declare module.exports: any;
}

declare module 'config-webpack/test-resources/testBlankNS' {
  declare module.exports: any;
}

declare module 'config-webpack/test-resources/testCustomConfig' {
  declare module.exports: any;
}

declare module 'config-webpack/test-resources/testCustomNS' {
  declare module.exports: any;
}

declare module 'config-webpack/test-resources/testDefaultNS' {
  declare module.exports: any;
}

declare module 'config-webpack/test/node-config-webpack.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'config-webpack/dist/ConfigWebpackPlugin.js' {
  declare module.exports: $Exports<'config-webpack/dist/ConfigWebpackPlugin'>;
}
declare module 'config-webpack/index' {
  declare module.exports: $Exports<'config-webpack'>;
}
declare module 'config-webpack/index.js' {
  declare module.exports: $Exports<'config-webpack'>;
}
declare module 'config-webpack/src/ConfigWebpackPlugin.js' {
  declare module.exports: $Exports<'config-webpack/src/ConfigWebpackPlugin'>;
}
declare module 'config-webpack/test-resources/testBlankNS.js' {
  declare module.exports: $Exports<'config-webpack/test-resources/testBlankNS'>;
}
declare module 'config-webpack/test-resources/testCustomConfig.js' {
  declare module.exports: $Exports<'config-webpack/test-resources/testCustomConfig'>;
}
declare module 'config-webpack/test-resources/testCustomNS.js' {
  declare module.exports: $Exports<'config-webpack/test-resources/testCustomNS'>;
}
declare module 'config-webpack/test-resources/testDefaultNS.js' {
  declare module.exports: $Exports<'config-webpack/test-resources/testDefaultNS'>;
}
declare module 'config-webpack/test/node-config-webpack.spec.js' {
  declare module.exports: $Exports<'config-webpack/test/node-config-webpack.spec'>;
}
