// flow-typed signature: 2def9dd05e68b6f9be82888332c729fe
// flow-typed version: <<STUB>>/jade-loader_v^0.8.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jade-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jade-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jade-loader/stringify.loader' {
  declare module.exports: any;
}

declare module 'jade-loader/test/extend.test' {
  declare module.exports: any;
}

declare module 'jade-loader/test/extend+include.test' {
  declare module.exports: any;
}

declare module 'jade-loader/test/fakeModuleSystem' {
  declare module.exports: any;
}

declare module 'jade-loader/test/include.test' {
  declare module.exports: any;
}

declare module 'jade-loader/web_modules/fs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jade-loader/index' {
  declare module.exports: $Exports<'jade-loader'>;
}
declare module 'jade-loader/index.js' {
  declare module.exports: $Exports<'jade-loader'>;
}
declare module 'jade-loader/stringify.loader.js' {
  declare module.exports: $Exports<'jade-loader/stringify.loader'>;
}
declare module 'jade-loader/test/extend.test.js' {
  declare module.exports: $Exports<'jade-loader/test/extend.test'>;
}
declare module 'jade-loader/test/extend+include.test.js' {
  declare module.exports: $Exports<'jade-loader/test/extend+include.test'>;
}
declare module 'jade-loader/test/fakeModuleSystem.js' {
  declare module.exports: $Exports<'jade-loader/test/fakeModuleSystem'>;
}
declare module 'jade-loader/test/include.test.js' {
  declare module.exports: $Exports<'jade-loader/test/include.test'>;
}
declare module 'jade-loader/web_modules/fs.js' {
  declare module.exports: $Exports<'jade-loader/web_modules/fs'>;
}
