// flow-typed signature: 8030dd855ddb439862b41f2076329203
// flow-typed version: <<STUB>>/safe-json-stringify_v~1.2.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'safe-json-stringify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'safe-json-stringify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'safe-json-stringify/index' {
  declare module.exports: $Exports<'safe-json-stringify'>;
}
declare module 'safe-json-stringify/index.js' {
  declare module.exports: $Exports<'safe-json-stringify'>;
}
